# Generated by Django 4.2.9 on 2024-01-18 23:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Furniture",
            fields=[
                (
                    "id_furniture",
                    models.IntegerField(primary_key=True, serialize=False),
                ),
                ("furniture_name", models.CharField(max_length=50)),
                ("count_part", models.IntegerField()),
                ("material", models.CharField(max_length=50)),
                ("weight", models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name="FurniturePart",
            fields=[
                ("id_part", models.IntegerField(primary_key=True, serialize=False)),
                ("part_name", models.CharField(max_length=50)),
                ("part_weight", models.FloatField(null=True)),
                ("unique_code", models.TextField()),
                ("flag", models.BooleanField(default=False)),
                (
                    "furniture_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Furniture_App.furniture",
                    ),
                ),
            ],
        ),
    ]
