# Generated by Django 4.2.9 on 2024-01-19 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Furniture_App", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="furniture",
            name="furniture_name",
            field=models.CharField(default="Название", max_length=50),
        ),
    ]
